import { clerkMiddleware, createRouteMatcher } from '@clerk/nextjs/server'

// Public routes — accessible to logged-out visitors AND search-engine
// crawlers. Anything NOT in this list goes through `auth.protect()` and
// gets redirected to /sign-in for unauthenticated requests.
//
// Why each entry matters:
//   /             — marketing landing
//   /landing      — public landing reachable by logged-in users too
//   /pricing      — pricing comparison (must be indexable)
//   /terms        — legal page (must be indexable)
//   /privacy      — legal page (must be indexable)
//   /sign-in(.*)  — Clerk hosted UI
//   /sign-up(.*)  — Clerk hosted UI
//   /api/paystack/webhook — incoming webhook signed by Paystack HMAC
//   /api/webhooks/clerk    — incoming Clerk webhook
//   /api/jumia/callback    — Jumia OAuth post-redirect
//   /api/cron/(.*)         — Vercel cron, bearer-token authorised
//   /extension              — Chrome extension marketing/onboarding page
//   /api/extension/fill     — the extension's autofill call. The extension has
//                            no Clerk browser session (it runs from Jumia's
//                            origin) — it authenticates itself with a
//                            PandaWorld API key checked inside the route (see
//                            lib/security/extension-keys.ts), not Clerk.
//   /api/extension/account   — same story: the panel's status row (plan +
//                            credits), authed by the same API key.
//   NOTE: /extension/dashboard and /api/extension/keys are intentionally NOT
//   listed here — they're the logged-in dashboard + its API, called by the
//   browser with a real Clerk session, so they go through the normal
//   auth.protect() gate below like any other app route.
//
// SEO convention routes — Next.js renders these as dynamic server
// routes (NOT static files), so they're caught by the matcher below
// and need explicit allow-list entries. Without these Google Search
// Console reports "Couldn't fetch" for /sitemap.xml because Clerk
// redirects the crawler to /sign-in.
//   /sitemap.xml       — generated by app/sitemap.ts
//   /robots.txt        — generated by app/robots.ts
//   /opengraph-image   — generated by app/opengraph-image.tsx
//   /favicon.ico       — usually static but defensive include
const isPublicRoute = createRouteMatcher([
  '/',
  '/landing',
  '/pricing',
  '/terms',
  '/privacy',
  '/sign-in(.*)',
  '/sign-up(.*)',
  '/api/paystack/webhook',
  '/api/webhooks/clerk',
  '/api/jumia/callback',
  '/api/cron/(.*)',
  '/extension',
  '/api/extension/fill',
  '/api/extension/account',
  // SEO + crawler routes — keep these PUBLIC or Google rejects the
  // sitemap and the OG link previews render as broken images.
  '/sitemap.xml',
  '/robots.txt',
  '/opengraph-image',
  '/opengraph-image(.*)',
  '/twitter-image',
  '/twitter-image(.*)',
  '/favicon.ico',
])

export default clerkMiddleware(async (auth, request) => {
  if (!isPublicRoute(request)) {
    await auth.protect()
  }
})

export const config = {
  matcher: [
    '/((?!_next|[^?]*\\.(?:html?|css|js(?!on)|jpe?g|webp|png|gif|svg|ttf|woff2?|ico|csv|docx?|xlsx?|zip|webmanifest)).*)',
    '/(api|trpc)(.*)',
  ],
}
