import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const dynamic = "force-dynamic";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

// ─── SEO metadata (root layout) ──────────────────────────────────────────────
//
// Single source of truth for:
//   - Site-wide <title> template (every page slots its own title in)
//   - Default description (overridden per page)
//   - Open Graph + Twitter card defaults (so WhatsApp / Twitter link
//     previews render the panda branding instead of a generic gray box)
//   - Canonical hostname (canonicalises pandaworldai-xyz.vercel.app
//     preview URLs back to pandaworldai.site so Google doesn't index
//     duplicate-content variants)
//   - Google Search Console verification tag
//
// Keep the description under 160 characters — that's the cap Google
// uses for SERP snippets. Above 160 gets truncated mid-sentence.

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://pandaworldai.site";

const HOME_TITLE = "Jumia listings from WhatsApp or Chrome | PandaWorld";
const HOME_DESCRIPTION =
  "Send product photos and a price on WhatsApp, or autofill Jumia Vendor Center from Chrome. You review the draft before it goes live. Free while we test. For Jumia sellers across Africa.";

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: {
    default:  HOME_TITLE,
    template: "%s · PandaWorld",
  },
  description: HOME_DESCRIPTION,
  applicationName: "PandaWorld",
  authors: [{ name: "PandaWorld" }],
  creator:   "PandaWorld",
  publisher: "PandaWorld",
  category:  "Business Software",
  // Canonical URL — tells Google "this is the real URL, ignore preview
  // and www variants". Per-page metadata can override this.
  alternates: {
    canonical: APP_URL,
  },
  // Open Graph — drives WhatsApp / Facebook / LinkedIn previews.
  // Critical for Ghana where most marketing happens via WhatsApp shares.
  //
  // The og:image itself is generated by app/opengraph-image.tsx
  // (Next.js convention — auto-rendered to /opengraph-image.png at
  // build time and auto-referenced in <head>). Don't set `images:` here
  // or Next.js will emit duplicate og:image tags.
  openGraph: {
    type:        "website",
    // Generic English locale — sellers across all 9 Jumia African
    // markets read the page; en_GH would be misleading for Nigerian /
    // Kenyan / Egyptian visitors. Open Graph treats "en_US" as the
    // default for English content without a specific regional fit.
    locale:      "en_US",
    url:         APP_URL,
    siteName:    "PandaWorld",
    title:       HOME_TITLE,
    description: HOME_DESCRIPTION,
  },
  twitter: {
    card:        "summary_large_image",
    title:       HOME_TITLE,
    description: HOME_DESCRIPTION,
  },
  // Google Search Console domain ownership.
  // To rotate this tag, swap the content string here — no other
  // touchpoint, since the Metadata API renders it into <head>.
  verification: {
    google: "IydEorSj09jedbfrhwFWb4M3X1WuPIggL8QQrfY68SM",
  },
  // Hint to crawlers what we want indexed. Per-page robots config
  // overrides this (e.g. /dashboard exports `robots: { index: false }`).
  robots: {
    index:        true,
    follow:       true,
    googleBot: {
      index:                   true,
      follow:                  true,
      "max-snippet":           -1,
      "max-image-preview":     "large",
      "max-video-preview":     -1,
    },
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={inter.variable}>
        <head>
          {/* Google Search Console domain ownership.
              The same tag is ALSO declared in the Metadata object above
              (verification.google) — that's the canonical Next.js path
              and produces an identical <meta> tag. Having both is
              harmless: Google handles duplicate verification meta tags
              fine, and the literal tag here means a quick "view source"
              on the live site shows the tag verbatim without trusting
              the metadata API. Remove either one once verification is
              complete; both have to be kept in sync if you rotate the
              code. */}
          <meta
            name="google-site-verification"
            content="IydEorSj09jedbfrhwFWb4M3X1WuPIggL8QQrfY68SM"
          />
        </head>
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
