import type { Metadata } from "next";
import Script from "next/script";
import { Inter_Tight } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { Analytics } from "@vercel/analytics/next";
import { FREE_SIGNUP_CREDITS } from "@/lib/billing/credit-packs";
import "./globals.css";

export const dynamic = "force-dynamic";

// Inter Tight site-wide — Inter with tighter default letter-spacing, the
// same face ListsGenie's site uses (requested 2026-09-27). Tailwind's
// `font-sans` reads this variable (tailwind.config.ts).
const interTight = Inter_Tight({
  subsets: ["latin"],
  variable: "--font-inter-tight",
  display: "swap",
});

// ─── SEO metadata (root layout) ──────────────────────────────────────────────
//
// Single source of truth for:
//   - Site-wide <title> template (every page slots its own title in)
//   - Default description (overridden per page)
//   - Open Graph + Twitter card defaults (so WhatsApp / Twitter link
//     previews render the panda branding instead of a generic gray box)
//   - Canonical hostname (canonicalises pandaworldai-xyz.vercel.app
//     preview URLs back to pandaworldai.site so Google doesn't index
//     duplicate-content variants)
//   - Google Search Console verification tag
//
// Keep the description under 160 characters — that's the cap Google
// uses for SERP snippets. Above 160 gets truncated mid-sentence.

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://pandaworldai.site";

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: {
    default:  "PandaWorld — AI Listing Assistant for Jumia Africa Sellers",
    template: "%s · PandaWorld",
  },
  description:
    "AI-powered product listings for Jumia sellers across Africa. Snap a photo, get a complete listing in seconds — category, attributes, images, pushed straight to Vendor Center. Works in Ghana, Nigeria, Kenya, Egypt, Morocco, and more.",
  applicationName: "PandaWorld",
  // Keyword set spans every Jumia market we technically support (the
  // onboarding flow already lists 9 countries). Per-country keywords
  // here drive long-tail SEO for "Jumia Nigeria tool" / "Jumia Kenya
  // listing app" style searches without diluting the core ranking.
  keywords: [
    "Jumia seller tool",
    "Jumia Vendor Center",
    "Jumia Africa",
    "Jumia Ghana",
    "Jumia Nigeria",
    "Jumia Kenya",
    "Jumia Egypt",
    "Jumia Morocco",
    "Jumia Senegal",
    "Jumia Ivory Coast",
    "Jumia Uganda",
    "AI product listing",
    "African e-commerce",
    "product upload Africa",
    "Jumia category picker",
    "Jumia QC",
    "product image background removal",
    "AI listing tool",
  ],
  authors: [{ name: "PandaWorld" }],
  creator:   "PandaWorld",
  publisher: "PandaWorld",
  category:  "Business Software",
  // Canonical URL — tells Google "this is the real URL, ignore preview
  // and www variants". Per-page metadata can override this.
  alternates: {
    canonical: APP_URL,
  },
  // Open Graph — drives WhatsApp / Facebook / LinkedIn previews.
  // Critical for Ghana where most marketing happens via WhatsApp shares.
  //
  // The og:image itself is generated by app/opengraph-image.tsx
  // (Next.js convention — auto-rendered to /opengraph-image.png at
  // build time and auto-referenced in <head>). Don't set `images:` here
  // or Next.js will emit duplicate og:image tags.
  openGraph: {
    type:        "website",
    // Generic English locale — sellers across all 9 Jumia African
    // markets read the page; en_GH would be misleading for Nigerian /
    // Kenyan / Egyptian visitors. Open Graph treats "en_US" as the
    // default for English content without a specific regional fit.
    locale:      "en_US",
    url:         APP_URL,
    siteName:    "PandaWorld",
    title:       "PandaWorld — AI Listing Assistant for Jumia Africa Sellers",
    description: "Snap a photo, get a complete Jumia listing in seconds. AI picks the category, fills attributes, polishes images, and pushes to Vendor Center. Works across Africa. Free for 5 listings every month.",
  },
  twitter: {
    card:        "summary_large_image",
    title:       "PandaWorld — AI Listing Assistant for Jumia Africa",
    description: "Snap a photo, get a complete Jumia listing in seconds. Free for 5 listings every month.",
  },
  // Google Search Console domain ownership.
  // To rotate this tag, swap the content string here — no other
  // touchpoint, since the Metadata API renders it into <head>.
  verification: {
    google: "IydEorSj09jedbfrhwFWb4M3X1WuPIggL8QQrfY68SM",
  },
  // Hint to crawlers what we want indexed. Per-page robots config
  // overrides this (e.g. /dashboard exports `robots: { index: false }`).
  robots: {
    index:        true,
    follow:       true,
    googleBot: {
      index:                   true,
      follow:                  true,
      "max-snippet":           -1,
      "max-image-preview":     "large",
      "max-video-preview":     -1,
    },
  },
};

// ─── JSON-LD structured data ─────────────────────────────────────────────────
//
// Two schemas, both relevant to PandaWorld:
//
//   1. Organization — gets us the knowledge-panel sidebar on the right
//      of Google SERPs for "PandaWorld" branded searches. Lists name,
//      logo, sameAs (social links), contactPoint.
//
//   2. SoftwareApplication — gets us the rich "Application" card with
//      price + offer category in SERPs for searches like "jumia
//      listing software". The offers block surfaces "GHS 0 / month
//      free trial" directly in search results.
//
// Both rendered as a single <script> tag in <head> via next/script.
// JSON.stringify is safe here — all values are static strings.

const organizationLd = {
  "@context":      "https://schema.org",
  "@type":         "Organization",
  name:            "PandaWorld",
  alternateName:   "PandaWorld AI",
  url:             APP_URL,
  // The OG image is wide (1200×630) rather than square, but Google
  // accepts it as a logo source. Upgrade to a dedicated square logo
  // once you have brand assets.
  logo:            `${APP_URL}/opengraph-image`,
  description:     "AI-powered product listing assistant for Jumia sellers across Africa.",
  foundingDate:    "2026",
  founders:        [{ "@type": "Person", name: "PandaWorld Team" }],
  // The legal entity is based in Accra (where the company is
  // registered + governed). That stays accurate even as we serve
  // sellers in other Jumia markets — Google reads this for the
  // knowledge-panel "headquarters" line.
  address: {
    "@type":          "PostalAddress",
    addressCountry:   "GH",
    addressLocality:  "Accra",
  },
  contactPoint: {
    "@type":         "ContactPoint",
    contactType:     "customer support",
    email:           "help.pandaworldai@gmail.com",
    availableLanguage: ["English"],
    // We serve every African country where Jumia operates. Each entry
    // gives Google a separate localised signal for SERPs in that
    // market (e.g. a Nigerian search for "Jumia listing tool" sees us
    // because areaServed includes NG).
    areaServed: [
      { "@type": "Country", name: "Ghana"        },
      { "@type": "Country", name: "Nigeria"      },
      { "@type": "Country", name: "Kenya"        },
      { "@type": "Country", name: "Egypt"        },
      { "@type": "Country", name: "Morocco"      },
      { "@type": "Country", name: "Senegal"      },
      { "@type": "Country", name: "Ivory Coast"  },
      { "@type": "Country", name: "Tanzania"     },
      { "@type": "Country", name: "Uganda"       },
    ],
  },
  sameAs: [
    // Linked socials — surfaces these as verified channels in Google's
    // knowledge panel + helps disambiguate "pandaworld" brand searches.
    // Single source of truth: lib/constants/support.ts SOCIAL_LINKS.
    "https://x.com/pandaworldai",
    "https://www.instagram.com/pandaworldai",
  ],
} as const;

const softwareApplicationLd = {
  "@context":        "https://schema.org",
  "@type":           "SoftwareApplication",
  name:              "PandaWorld",
  operatingSystem:   "Web",
  applicationCategory: "BusinessApplication",
  description:       "AI-powered listing assistant for Jumia sellers across Africa. Auto-generates titles, descriptions, categories, attributes, and product images. Pushes listings to Jumia Vendor Center.",
  url:               APP_URL,
  // Only the free sign-up offer, which is true whether or not billing is
  // switched on (lib/billing/mode.ts). The paid credit packs are listed
  // on /pricing, which reads the switch, rather than here: this layout is
  // static and can't know whether packs are on sale right now.
  offers: [
    { "@type": "Offer", name: "Free", price: "0", priceCurrency: "GHS", description: `${FREE_SIGNUP_CREDITS} free credits when you sign up` },
  ],
  audience: {
    "@type":        "Audience",
    audienceType:   "Jumia sellers across Africa",
    // No single geographicArea — we serve nine Jumia markets. Listing
    // them all here would over-stuff the schema; the Organization's
    // `areaServed` array already covers the full footprint.
  },
} as const;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider signInUrl="/sign-in" signUpUrl="/sign-up">
      <html lang="en" className={interTight.variable}>
        <head>
          {/* Google Search Console domain ownership.
              The same tag is ALSO declared in the Metadata object above
              (verification.google) — that's the canonical Next.js path
              and produces an identical <meta> tag. Having both is
              harmless: Google handles duplicate verification meta tags
              fine, and the literal tag here means a quick "view source"
              on the live site shows the tag verbatim without trusting
              the metadata API. Remove either one once verification is
              complete; both have to be kept in sync if you rotate the
              code. */}
          <meta
            name="google-site-verification"
            content="IydEorSj09jedbfrhwFWb4M3X1WuPIggL8QQrfY68SM"
          />

          {/* JSON-LD structured data — rendered as raw text inside a
              script tag with type="application/ld+json". Two separate
              scripts so we can iterate one without invalidating the
              other; Google parses each independently. */}
          <Script
            id="ld-organization"
            type="application/ld+json"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationLd) }}
          />
          <Script
            id="ld-software-application"
            type="application/ld+json"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareApplicationLd) }}
          />
        </head>
        <body>
          {children}
          <Analytics />
        </body>
      </html>
    </ClerkProvider>
  );
}
