import type { Metadata } from "next";
import Script from "next/script";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";

export const dynamic = "force-dynamic";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

// ─── SEO metadata (root layout) ──────────────────────────────────────────────
//
// Single source of truth for:
//   - Site-wide <title> template (every page slots its own title in)
//   - Default description (overridden per page)
//   - Open Graph + Twitter card defaults (so WhatsApp / Twitter link
//     previews render the panda branding instead of a generic gray box)
//   - Canonical hostname (canonicalises pandaworldai-xyz.vercel.app
//     preview URLs back to pandaworldai.site so Google doesn't index
//     duplicate-content variants)
//   - Google Search Console verification tag
//
// Keep the description under 160 characters — that's the cap Google
// uses for SERP snippets. Above 160 gets truncated mid-sentence.

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? "https://pandaworldai.site";

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: {
    default:  "PandaWorld — AI Listing Assistant for Jumia Ghana Sellers",
    template: "%s · PandaWorld",
  },
  description:
    "AI-powered product listings for Jumia Ghana. Snap a photo, get a complete listing in seconds — category, attributes, images, pushed straight to Vendor Center.",
  applicationName: "PandaWorld",
  keywords: [
    "Jumia Ghana",
    "Jumia seller tool",
    "Jumia Vendor Center",
    "AI product listing",
    "Ghana e-commerce",
    "product upload Ghana",
    "Jumia category picker",
    "Jumia QC",
    "Accra software company",
    "product image background removal",
    "AI listing tool",
  ],
  authors: [{ name: "PandaWorld" }],
  creator:   "PandaWorld",
  publisher: "PandaWorld",
  category:  "Business Software",
  // Canonical URL — tells Google "this is the real URL, ignore preview
  // and www variants". Per-page metadata can override this.
  alternates: {
    canonical: APP_URL,
  },
  // Open Graph — drives WhatsApp / Facebook / LinkedIn previews.
  // Critical for Ghana where most marketing happens via WhatsApp shares.
  //
  // The og:image itself is generated by app/opengraph-image.tsx
  // (Next.js convention — auto-rendered to /opengraph-image.png at
  // build time and auto-referenced in <head>). Don't set `images:` here
  // or Next.js will emit duplicate og:image tags.
  openGraph: {
    type:        "website",
    locale:      "en_GH",
    url:         APP_URL,
    siteName:    "PandaWorld",
    title:       "PandaWorld — AI Listing Assistant for Jumia Ghana Sellers",
    description: "Snap a photo, get a complete Jumia listing in seconds. AI picks the category, fills attributes, polishes images, and pushes to Vendor Center. Free for 5 listings every month.",
  },
  twitter: {
    card:        "summary_large_image",
    title:       "PandaWorld — AI Listing Assistant for Jumia Ghana",
    description: "Snap a photo, get a complete Jumia listing in seconds. Free for 5 listings every month.",
  },
  // Google Search Console domain ownership.
  // To rotate this tag, swap the content string here — no other
  // touchpoint, since the Metadata API renders it into <head>.
  verification: {
    google: "IydEorSj09jedbfrhwFWb4M3X1WuPIggL8QQrfY68SM",
  },
  // Hint to crawlers what we want indexed. Per-page robots config
  // overrides this (e.g. /dashboard exports `robots: { index: false }`).
  robots: {
    index:        true,
    follow:       true,
    googleBot: {
      index:                   true,
      follow:                  true,
      "max-snippet":           -1,
      "max-image-preview":     "large",
      "max-video-preview":     -1,
    },
  },
};

// ─── JSON-LD structured data ─────────────────────────────────────────────────
//
// Two schemas, both relevant to PandaWorld:
//
//   1. Organization — gets us the knowledge-panel sidebar on the right
//      of Google SERPs for "PandaWorld" branded searches. Lists name,
//      logo, sameAs (social links), contactPoint.
//
//   2. SoftwareApplication — gets us the rich "Application" card with
//      price + offer category in SERPs for searches like "jumia
//      listing software". The offers block surfaces "GHS 0 / month
//      free trial" directly in search results.
//
// Both rendered as a single <script> tag in <head> via next/script.
// JSON.stringify is safe here — all values are static strings.

const organizationLd = {
  "@context":      "https://schema.org",
  "@type":         "Organization",
  name:            "PandaWorld",
  alternateName:   "PandaWorld AI",
  url:             APP_URL,
  // The OG image is wide (1200×630) rather than square, but Google
  // accepts it as a logo source. Upgrade to a dedicated square logo
  // once you have brand assets.
  logo:            `${APP_URL}/opengraph-image`,
  description:     "AI-powered product listing assistant for Jumia Ghana sellers.",
  foundingDate:    "2026",
  founders:        [{ "@type": "Person", name: "PandaWorld Team" }],
  address: {
    "@type":          "PostalAddress",
    addressCountry:   "GH",
    addressLocality:  "Accra",
  },
  contactPoint: {
    "@type":         "ContactPoint",
    contactType:     "customer support",
    email:           "help.pandaworldai@gmail.com",
    availableLanguage: ["English"],
    areaServed:      "GH",
  },
  sameAs: [
    // Add socials here once they exist (Twitter, LinkedIn, etc.)
  ],
} as const;

const softwareApplicationLd = {
  "@context":        "https://schema.org",
  "@type":           "SoftwareApplication",
  name:              "PandaWorld",
  operatingSystem:   "Web",
  applicationCategory: "BusinessApplication",
  description:       "AI-powered listing assistant for Jumia Ghana sellers. Auto-generates titles, descriptions, categories, attributes, and product images. Pushes listings to Jumia Vendor Center.",
  url:               APP_URL,
  offers: [
    { "@type": "Offer", name: "Free",     price: "0",   priceCurrency: "GHS", description: "5 listings every month" },
    { "@type": "Offer", name: "Starter",  price: "30",  priceCurrency: "GHS", description: "30 listings + 10 image polishes / month" },
    { "@type": "Offer", name: "Pro",      price: "65",  priceCurrency: "GHS", description: "100 listings + 30 image polishes / month" },
    { "@type": "Offer", name: "Business", price: "120", priceCurrency: "GHS", description: "500 listings + 150 image polishes / month" },
  ],
  audience: {
    "@type":        "Audience",
    audienceType:   "Jumia Ghana sellers",
    geographicArea: { "@type": "Country", name: "Ghana" },
  },
} as const;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className={inter.variable}>
        <head>
          {/* JSON-LD structured data — rendered as raw text inside a
              script tag with type="application/ld+json". Two separate
              scripts so we can iterate one without invalidating the
              other; Google parses each independently. */}
          <Script
            id="ld-organization"
            type="application/ld+json"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(organizationLd) }}
          />
          <Script
            id="ld-software-application"
            type="application/ld+json"
            strategy="beforeInteractive"
            dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareApplicationLd) }}
          />
        </head>
        <body>{children}</body>
      </html>
    </ClerkProvider>
  );
}
