import Link from "next/link";
import { MarketingFooter } from "@/components/marketing/footer";
import { Wordmark } from "@/components/marketing/wordmark";

// ─── Public Terms of Service ─────────────────────────────────────────────────
//
// DRAFT TEMPLATE — review with a Ghana-qualified lawyer before public
// launch. Covers the structural points a SaaS ToS needs to make:
// service description, payment terms, refunds, IP, acceptable use,
// limitation of liability, governing law. Tailored to:
//   - Ghana jurisdiction (Data Protection Act 2012)
//   - Paystack-mediated payments in GHS
//   - Jumia OAuth integration
//   - The actual feature set we ship (AI listing generation, image
//     enhancement, Vendor Center push)
//
// Sections are numbered for easy reference if Support ever has to
// quote one to a seller in a dispute.

export const metadata = {
  title:       "Terms of Service · PandaWorld",
  description: "Terms of Service for using PandaWorld — the AI-powered Jumia Ghana listing assistant.",
};

const LAST_UPDATED = "2026-05-20";
const COMPANY_NAME = "PandaWorld"; // Update once a legal entity is registered

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white text-zinc-900">
      <SimpleNav active="terms" />

      <main className="mx-auto max-w-3xl px-6 py-16">
        <div>
          <p className="text-xs font-semibold uppercase tracking-widest text-orange-500">
            Legal
          </p>
          <h1 className="mt-2 text-3xl font-bold tracking-tight sm:text-4xl">
            Terms of Service
          </h1>
          <p className="mt-3 text-sm text-zinc-500">
            Last updated: {LAST_UPDATED}
          </p>
        </div>

        <div className="prose prose-sm prose-zinc mt-10 max-w-none">
          <p>
            These Terms of Service (&quot;Terms&quot;) govern your use of{" "}
            <strong>{COMPANY_NAME}</strong> (&quot;we&quot;,{" "}
            &quot;us&quot;, &quot;the Service&quot;), an AI-powered listing
            assistant for sellers on Jumia Ghana. By creating an account or
            using the Service, you agree to these Terms. If you do not
            agree, do not use the Service.
          </p>

          <h2>1. Who can use {COMPANY_NAME}</h2>
          <p>
            You must be at least 18 years old and legally able to enter into a
            contract under Ghanaian law. The Service is intended for active
            Jumia Ghana sellers — you must hold a valid Vendor Center
            account in good standing.
          </p>

          <h2>2. What the Service does</h2>
          <p>
            {COMPANY_NAME} helps you create product listings by using
            artificial intelligence to: identify the appropriate Jumia
            category from your images, fill required product attributes,
            polish or rebuild product images, and push the resulting
            listing to Jumia Vendor Center on your behalf. You retain
            full responsibility for reviewing AI-generated content before
            submission.
          </p>

          <h2>3. Accuracy of AI output</h2>
          <p>
            AI can make mistakes. Categories, attributes, descriptions
            and images generated by the Service may be inaccurate,
            incomplete or non-compliant with Jumia&apos;s policies. You
            agree to review every listing before pushing it to Jumia,
            and you accept that Jumia&apos;s quality-control team has
            sole authority to approve or reject listings. We are not
            responsible for QC rejections, account suspensions, or any
            commercial loss arising from AI errors.
          </p>

          <h2>4. Plans, billing and refunds</h2>
          <p>
            The Free plan allows up to 5 product listings. The Pro plan
            (GHS 50 / month) is billed monthly in advance via Paystack
            and grants unlimited listings, image rebuild, and priority
            support. You may cancel from your billing settings at any
            time; cancellation takes effect at the end of the current
            billing period.
          </p>
          <p>
            All sales are <strong>final</strong>. We do not offer pro-rated
            refunds for unused time within a billing period. If you
            believe you were charged in error, contact support within 7
            days of the charge and we will investigate; refunds are
            granted at our discretion.
          </p>
          <p>
            Pricing may change with 30 days&apos; notice via email or
            in-app notification. Continued use of the Service after a
            price change constitutes acceptance of the new price.
          </p>

          <h2>5. Your content</h2>
          <p>
            You retain all rights in the product images, descriptions,
            and other materials you upload (&quot;Your Content&quot;).
            You grant us a non-exclusive licence to process, store,
            transform, and transmit Your Content for the sole purpose of
            providing the Service — including sending it to third-party
            AI providers (Google Gemini), image processing providers
            (PhotoRoom), and Jumia.
          </p>
          <p>
            You represent that you own or are authorised to use all
            Content you upload, and that the Content does not infringe
            any third-party intellectual property right. You are solely
            responsible for ensuring you have permission to list any
            branded products and that you comply with Jumia&apos;s
            anti-counterfeit and brand-authorisation policies.
          </p>

          <h2>6. Acceptable use</h2>
          <p>You will not:</p>
          <ul>
            <li>Use the Service to list counterfeit, illegal, or restricted goods;</li>
            <li>Misrepresent product authenticity, condition, brand or origin;</li>
            <li>Upload images you do not own or have rights to;</li>
            <li>Attempt to bypass Jumia&apos;s QC checks or marketplace policies;</li>
            <li>Reverse-engineer, scrape, or build a competing service from our outputs;</li>
            <li>Probe, scan or test the vulnerability of the Service without prior written permission;</li>
            <li>Share your account credentials with any third party.</li>
          </ul>
          <p>
            We may suspend or terminate accounts that violate these
            rules, with or without notice. Jumia&apos;s own terms also
            apply to the listings you create; we do not override them.
          </p>

          <h2>7. Third-party services</h2>
          <p>
            The Service relies on third parties to function — including
            Jumia (marketplace), Clerk (authentication), Supabase
            (database and storage), Google (Gemini AI), PhotoRoom
            (image processing), and Paystack (payments). Their terms
            and privacy policies apply to the data flows they process.
            We are not responsible for outages, errors, or data losses
            caused by any third-party service.
          </p>

          <h2>8. Data privacy</h2>
          <p>
            Our handling of personal data is governed by our{" "}
            <Link href="/privacy" className="text-orange-600 underline">
              Privacy Policy
            </Link>
            , which forms part of these Terms. We comply with the Ghana
            Data Protection Act, 2012 (Act 843).
          </p>

          <h2>9. Account suspension and termination</h2>
          <p>
            We may suspend or terminate your account immediately if you
            breach these Terms, if your payment fails after reasonable
            notice, or if Jumia revokes your Vendor Center access. You
            may delete your account at any time from Settings; on
            deletion we revoke Jumia tokens, cancel any active
            subscription, and permanently remove your listings and
            uploaded images after a 30-day grace period.
          </p>

          <h2>10. Limitation of liability</h2>
          <p>
            To the maximum extent permitted by Ghanaian law, the Service
            is provided <strong>&quot;as is&quot;</strong> without
            warranties of any kind, express or implied — including
            merchantability, fitness for a particular purpose, and
            non-infringement. We do not warrant that the Service will
            be uninterrupted, error-free, or that AI outputs will be
            accurate or accepted by Jumia.
          </p>
          <p>
            Our total liability to you for any claim arising out of or
            relating to the Service shall not exceed the greater of
            (a) the amount you paid us in the 12 months preceding the
            claim or (b) GHS 1,000. We are not liable for indirect,
            incidental, consequential, special or punitive damages,
            including lost profits, lost sales, or reputational harm.
          </p>

          <h2>11. Indemnification</h2>
          <p>
            You agree to indemnify and hold us harmless from any claim,
            demand, loss or damage (including reasonable legal fees)
            arising out of your use of the Service, your breach of
            these Terms, or your violation of any law or third-party
            right (including Jumia&apos;s marketplace policies, brand
            owners&apos; intellectual property rights, and Ghana&apos;s
            consumer protection laws).
          </p>

          <h2>12. Changes to these Terms</h2>
          <p>
            We may update these Terms from time to time. Material
            changes will be communicated via email or an in-app notice
            at least 14 days before they take effect. Continued use of
            the Service after the effective date constitutes acceptance
            of the updated Terms.
          </p>

          <h2>13. Governing law and disputes</h2>
          <p>
            These Terms are governed by the laws of the Republic of
            Ghana. Any dispute arising out of or relating to these
            Terms or the Service shall be resolved by the courts of
            Accra, Ghana, which shall have exclusive jurisdiction. The
            parties shall first attempt to resolve any dispute by
            good-faith negotiation for 30 days before initiating legal
            proceedings.
          </p>

          <h2>14. Contact</h2>
          <p>
            Questions about these Terms? Reach us via the WhatsApp
            support button inside the app, or email{" "}
            <a
              href="mailto:help.pandaworldai@gmail.com"
              className="text-orange-600 underline"
            >
              help.pandaworldai@gmail.com
            </a>
            .
          </p>

          <hr />
          <p className="text-xs text-zinc-500">
            <strong>Notice:</strong> This document is a draft template.
            Before launching publicly, have it reviewed by a Ghana-qualified
            lawyer to confirm compliance with the Electronic Transactions
            Act, 2008 (Act 772), the Data Protection Act, 2012 (Act 843),
            the Consumer Protection Act, 2024, and Paystack&apos;s
            merchant agreement.
          </p>
        </div>
      </main>

      <MarketingFooter />
    </div>
  );
}

// Shared simple nav for legal pages
function SimpleNav({ active }: { active: "terms" | "privacy" }) {
  return (
    <header className="sticky top-0 z-20 border-b border-zinc-100 bg-white/80 backdrop-blur">
      <div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4">
        <Link href="/" aria-label="pandaworld home">
          <Wordmark size={28} />
        </Link>
        <nav className="flex items-center gap-1 sm:gap-4">
          {/* Terms + Privacy intentionally non-responsive — these
              pages need a lawyer review before public link-out. */}
          <span
            className="cursor-not-allowed rounded-md px-3 py-1.5 text-sm font-medium text-zinc-300"
            aria-disabled="true"
          >
            Terms
          </span>
          <span
            className="cursor-not-allowed rounded-md px-3 py-1.5 text-sm font-medium text-zinc-300"
            aria-disabled="true"
          >
            Privacy
          </span>
          <Link
            href="/pricing"
            className="rounded-md px-3 py-1.5 text-sm font-medium text-zinc-600 hover:bg-zinc-50 hover:text-zinc-900"
          >
            Pricing
          </Link>
          <Link
            href="/sign-up"
            className="rounded-md bg-orange-500 px-3 py-1.5 text-sm font-semibold text-white shadow-sm transition-colors hover:bg-orange-600"
          >
            Get started
          </Link>
        </nav>
      </div>
    </header>
  );
}
