-- Index the lookup the feed-status cron runs every minute.
--
-- /api/cron/jumia-feeds asks one question on every tick:
--
--   select id, user_id, jumia_ref, title, whatsapp_batch_id
--   from listings
--   where status = 'pending_approval' and jumia_ref is not null;
--
-- There is no index on listings.status. The only index this repo has ever
-- created on the table is listings_whatsapp_batch_id_idx
-- (2026-09-12_whatsapp-batches.sql), so that query is a sequential scan of
-- every listing on the platform, run 1,440 times a day, and it grows with
-- the catalogue rather than with the handful of rows it actually wants.
--
-- Why that matters more here than it looks: PostgREST on this project is
-- already known to kill its own threads on slow queries — "Warp server
-- error: Thread killed by timeout manager", measured at roughly 11% of
-- worker ticks (see the withRetry note in lib/whatsapp/analysis-queue.ts).
-- A scan that takes too long fails the same way every time, not
-- occasionally, and until now that failure was invisible: the route
-- discarded the query error, so a dead poll and an idle one both answered
-- 200 {checked: 0} with no log line at all.
--
-- The matching seller-facing symptom, reported 2026-09-15: submitted
-- listings stayed at "pending Jumia review" indefinitely and only moved
-- when the seller opened /extension/whatsapp-listings, whose own refresh
-- does the same work — but scoped to one user_id, so it reads a handful of
-- rows instead of the whole table.
--
-- Partial on jumia_ref because the query always requires it, which keeps
-- the index to just the rows in flight: a listing that is live, failed or
-- still a draft is not in it at all, so it stays small no matter how big
-- the catalogue gets.
create index if not exists listings_pending_feed_idx
  on listings (status)
  where jumia_ref is not null;
