-- Category embeddings — pgvector column + similarity index for
-- smarter, semantic category retrieval during AI auto-analyze.
--
-- Why this migration:
--   The current category retrieval (lib/jumia/category-search.ts →
--   searchCategoriesByText) is a fuzzy lexical match against
--   category names. Works for English product names that share
--   vocabulary with the category tree ("Phone case" → "Mobile
--   Accessories > Phone Cases"). Fails for:
--     - Non-English product names ("Kente cloth", "Akpeteshie")
--     - Brand-specific products ("AirPods Pro" → which category?)
--     - Vague descriptions ("a thing to keep food cold")
--
--   Embeddings turn this into semantic similarity: we embed the
--   product description and each category path into 768-dim vectors,
--   then find the categories whose vectors are CLOSEST to the
--   product vector (cosine similarity). Captures meaning, not just
--   word overlap.
--
-- Read path (lib/jumia/category-search.ts after this migration):
--   1. embedText(productDescription) → vector(768)
--   2. SELECT * FROM jumia_categories ORDER BY embedding <=> $1 LIMIT 8
--      (<=> is pgvector's cosine-distance operator; smallest = nearest)
--   3. Pass top-8 candidates to Pass B for AI ranking
--
-- Write path:
--   - On category sync (lib/jumia/categories.ts), generate embedding
--     for each new/updated category and write to this column
--   - Manual backfill route: /api/admin/embed-categories
--
-- Apply via Supabase Dashboard → SQL Editor → New query → paste → Run.
-- pgvector ships pre-installed on Supabase; the CREATE EXTENSION is
-- idempotent and a no-op if already enabled.

-- ── 1. Enable pgvector ─────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS vector;

-- ── 2. Add embedding column ────────────────────────────────────────────────
-- text-embedding-004 returns 768-dim vectors. If we ever swap to a
-- different model with a different dimension, this column would need
-- to be dropped + recreated (pgvector doesn't allow ALTER COLUMN TYPE
-- for vector dimensions).
ALTER TABLE jumia_categories
  ADD COLUMN IF NOT EXISTS embedding vector(768);

COMMENT ON COLUMN jumia_categories.embedding IS
  'Semantic embedding of the category path, generated by Google text-embedding-004 (768 dim). Used for cosine-similarity retrieval in lib/jumia/category-search.ts → searchCategoriesByEmbedding(). Generated on initial sync + by /api/admin/embed-categories for backfill.';

-- ── 3. Similarity index ────────────────────────────────────────────────────
-- ivfflat is the standard pgvector index for cosine-similarity
-- queries. `lists = 100` is a good default for our ~10k category
-- table — Supabase docs recommend `sqrt(N) lists`, so ~100 for 10k
-- rows. The query planner will use this index automatically when we
-- query `ORDER BY embedding <=> $1 LIMIT N`.
--
-- Note: ivfflat indexes must be built AFTER you have data. Building
-- on an empty table is fine but the index efficiency only kicks in
-- once enough rows have embeddings populated. If you create the
-- index then immediately backfill, that's the recommended sequence
-- (the index just rebuilds itself periodically).
CREATE INDEX IF NOT EXISTS idx_jumia_categories_embedding
  ON jumia_categories
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

-- ── 4. (Optional) Partial filter for categories without embeddings ─────────
-- Lets the backfill route find unembedded categories fast.
CREATE INDEX IF NOT EXISTS idx_jumia_categories_missing_embedding
  ON jumia_categories (code)
  WHERE embedding IS NULL;

-- ── 5. RPC: search_categories_by_embedding ────────────────────────────────
-- Lets the app call cosine-similarity search via Supabase's PostgREST
-- without writing raw SQL on every request. The Supabase JS client
-- calls this via .rpc('search_categories_by_embedding', {...}).
--
-- Returns: rows sorted by similarity (1 = identical, 0 = orthogonal),
-- limited to match_limit. Only listable categories (with an
-- attribute_set_sid) are returned — matches the rest of the pipeline.
--
-- Cosine distance via <=> returns 0..2; we convert to similarity
-- with (1 - dist / 2) clamped to [0, 1]. For normalised embeddings
-- (which text-embedding-004 returns) this is equivalent to true
-- cosine similarity.
CREATE OR REPLACE FUNCTION search_categories_by_embedding(
  query_embedding vector(768),
  match_limit     int DEFAULT 8
)
RETURNS TABLE (
  code              integer,
  name              text,
  path              text,
  attribute_set_sid text,
  similarity        float
)
LANGUAGE sql
STABLE
AS $$
  SELECT
    jc.code,
    jc.name,
    jc.path,
    jc.attribute_set_sid,
    GREATEST(0.0, LEAST(1.0, 1.0 - (jc.embedding <=> query_embedding) / 2.0))::float AS similarity
  FROM jumia_categories jc
  WHERE jc.embedding IS NOT NULL
    AND jc.attribute_set_sid IS NOT NULL
  ORDER BY jc.embedding <=> query_embedding
  LIMIT match_limit;
$$;

COMMENT ON FUNCTION search_categories_by_embedding IS
  'Cosine-similarity search over jumia_categories.embedding. Used by lib/jumia/category-search.ts → searchCategoriesByEmbedding(). Returns top-N nearest categories scored 0–1.';
